py3 fix for writing out tosca data
fixes:

  File "/home/psherratt/cloudshell/env/lib/python3.6/site-packages/shellfoundry/utilities/modifiers/definition/definition_modification.py", line 42, in edit_tosca_meta
    tosca_file.writelines(tosca_data)
TypeError: a bytes-like object is required, not 'str'